routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GarageController@index');

Route::resource('garage','GarageController');

Route::resource('carbjetting','CarbController');

Route::resource('drive','DriveController');

Route::resource('journal','JournalController');

Route::resource('suspension','SuspensionController');

Auth::routes();

/*Route::get('/home', [
    'middleware' => ['auth'],
    'uses' => function () {
        echo "You are allowed to view this page!";
    }]);*/

app/Drive.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Drive extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
         'garage_id', 'chain', 'front_sprocket', 'rear_sprocket', 'links', 'slack'
    ];


    /**
     * Get the garage record associated with the drive item.
     */
    public function garage()
    {
        return $this->belongsTo('App\Garage', 'garage_id');
    }

}

app/Http/Controllers/DriveController.php
<?php

namespace App\Http\Controllers;

use App\Drive;
use Illuminate\Http\Request;

class DriveController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('drive.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'chain' => 'required',
            'front_sprocket' => 'required',
            'rear_sprocket' => 'required',
            'links' => 'required',
        ]);


        Drive::create($request->all());
        return redirect()->route('garage.show', [$request->get('garage_id')])
            ->with('success','Drive record created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/drive/create.blade.php
@extends('layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add </h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('drive.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if (count($errors) < 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    {!! Form::open(array('route' => 'drive.store','method'=>'POST')) !!}
    @include('drive.form')
    {!! Form::close() !!}


@endsection

resources/views/drive/edit.blade.php
@extends('layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Vehicle</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('garage.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    {!! Form::model($drive, ['method' => 'PATCH','route' => ['drive.update', $drive->id]]) !!}
    @include('drive.form', [$drive->id])
    {!! Form::close() !!}


@endsection

resources/views/drive/form.blade.php
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            {!! Form::hidden('garage_id', request('id'), null) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Chain:</strong>
            {!! Form::text('chain', null, array('placeholder' => 'Chain','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Front Sprocket:</strong>
            {!! Form::text('front_sprocket', null, array('placeholder' => 'Front Sprocket','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Rear Sprocket</strong>
            {!! Form::text('rear_sprocket', null, array('placeholder' => 'Rear Sprocket','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Number of Links</strong>
            {!! Form::text('links', null, array('placeholder' => 'Number of Links','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Chain Slack</strong>
            {!! Form::text('slack', null, array('placeholder' => 'Chain Slack','class' => 'form-control')) !!}
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/drive/index.blade.php
<h2>Drivetrain</h2>

<a class="btn btn-success" href="{{ route('drive.create', [$garage->id]) }}"> Add Drive</a>

@if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
@endif

<table class="table table-bordered">
    <tr>
        <th>Chain</th>
        <th>Front Sprocket</th>
        <th>Rear Sprocket</th>
        <th>Links</th>
        <th>Slack</th>
    </tr>

          <tr>
              <td>{{ $garage->drive}}</td>
              <td>{{ $garage->front_sprocket}}</td>
              <td>{{ $garage->rear_sprocket}}</td>
              <td>{{ $garage->links}}</td>
              <td>{{ $garage->slack}}</td>
              <td>
                  <a class="btn btn-primary" href="{{ route('drive.edit',$garage->id) }}">Edit</a>
                  {!! Form::open(['method' => 'DELETE','route' => ['drive.destroy', $garage->id],'style'=>'display:inline']) !!}
                  {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                  {!! Form::close() !!}
              </td>
          </tr>

</table>

resources/views/drive/show.blade.php
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2><strong>Drive</strong></h2>
        </div>

        <div style="float: right">
            <a class="btn btn-primary" href="{{ route('drive.edit',$garage->id) }}">Edit</a>

            {!! Form::open(['method' => 'DELETE','route' => ['drive.destroy', $garage->id],'style'=>'float:right']) !!}
            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
            {!! Form::close() !!}
        </div>

    </div>
</div>

@foreach ($garage->drive as $drive)

<table class="table table-bordered">
    <tr>
        <th>Chain</th>
        <th>Front Sprocket</th>
        <th>Rear Sprocket</th>
        <th>Links</th>
        <th>Slack</th>
    </tr>

    <tr>
        <td>{{ $drive->chain}}</td>
        <td>{{ $drive->front_sprocket}}</td>
        <td>{{ $drive->rear_sprocket}}</td>
        <td>{{ $drive->links}}</td>
        <td>{{ $drive->slack}}</td>
    </tr>
</table>

@endforeach