routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GarageController@index');

Route::resource('garage','GarageController');

Route::resource('carbjetting','CarbController');

Route::resource('drive','DriveController');

Route::resource('journal','JournalController');

Route::resource('suspension','SuspensionController');

Auth::routes();

/*Route::get('/home', [
    'middleware' => ['auth'],
    'uses' => function () {
        echo "You are allowed to view this page!";
    }]);*/

app/Journal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Journal extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'garage_id','date','location', 'seat_time', 'notes'
    ];


    /**
     * Get the garage record associated with the drive item.
     */
    public function garage()
    {
        return $this->belongsTo('App\Garage', 'garage_id');
    }
}

app/Http/Controllers/JournalController.php
<?php

namespace App\Http\Controllers;

use App\Journal;
use Illuminate\Http\Request;

class JournalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('journal.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'location' => 'required',
            'date' => 'required',
            'seat_time' => 'required',
            'notes' => 'required',
        ]);

        Journal::create($request->all());
        return redirect()->route('garage.show', [$request->get('garage_id')])
            ->with('success','Journal record created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/journal/create.blade.php
@extends('layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Journal entry</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('journal.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if (count($errors) < 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    {!! Form::open(array('route' => 'journal.store','method'=>'POST')) !!}
    @include('journal.form')
    {!! Form::close() !!}


@endsection

resources/views/journal/edit.blade.php
@extends('layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Vehicle</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('garage.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    {!! Form::model($garage, ['method' => 'PATCH','route' => ['garage.update', $garage->id]]) !!}
    @include('garage.form')
    {!! Form::close() !!}


@endsection

resources/views/journal/form.blade.php
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            {!! Form::hidden('garage_id', request('id'), null) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Date</strong>
            {!! Form::text('date', null, array('placeholder' => 'Date','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Location</strong>
            {!! Form::text('location', null, array('placeholder' => 'Location','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Seat Time</strong>
            {!! Form::text('seat_time', null, array('placeholder' => 'Seat Time','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Notes</strong>
            {!! Form::text('notes', null, array('placeholder' => 'Notes','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/journal/index.blade.php
@extends('layout')

<h2>Ride Journal</h2>

@if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
@endif


<table class="table table-bordered">
    <tr>
        <th>Date</th>
        <th>Location</th>
        <th>Seat Time</th>
        <th>Notes</th>
    </tr>




   <tr>
        <td>{{ $garages->journal->date}}</td>
        <td>{{ $journal->location}}</td>
        <td>{{ $journal->seat_time}}</td>
        <td>{{ $journal->notes}}</td>
    </tr>


</table>

resources/views/journal/show.blade.php
<div class="row">
    <div class="col-lg-12 margin-tb">
        <h2><strong>Ride Journal</strong>
            <div style="float: right">
                <a class="btn btn-primary" href="{{ route('journal.edit',$garage->id) }}">Edit</a>
                {!! Form::open(['method' => 'DELETE','route' => ['journal.destroy', $garage->id],'style'=>'float:right']) !!}
                {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                {!! Form::close() !!}
            </div>
        </h2>
    </div>
</div>

@foreach ($garage->journal as $journal)

    <table class="table table-bordered">
        <tr>
            <th>Date</th>
            <th>Location</th>
            <th>Seat Time</th>
            <th>Notes</th>
        </tr>

        <tr>
            <td>{{ $journal->date}}</td>
            <td>{{ $journal->location}}</td>
            <td>{{ $journal->seat_time}}</td>
            <td>{{ $journal->notes}}</td>
        </tr>
    </table>

@endforeach