routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GarageController@index');

Route::resource('garage','GarageController');

Route::resource('carbjetting','CarbController');

Route::resource('drive','DriveController');

Route::resource('journal','JournalController');

Route::resource('suspension','SuspensionController');

Auth::routes();

/*Route::get('/home', [
    'middleware' => ['auth'],
    'uses' => function () {
        echo "You are allowed to view this page!";
    }]);*/

app/carbJetting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class carbJetting extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'garage_id', 'pilot', 'main', 'needle', 'clip_pos', 'float_height', 'idle_screw', 'airfuel_screw'
    ];


    /**
     * Get the garage record associated with the drive item.
     */
    public function garage()
    {
        return $this->belongsTo('App\Garage', 'garage_id');
    }

}

resources/views/carbjetting/create.blade.php
@extends('layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('carbjetting.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if (count($errors) < 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    {!! Form::open(array('route' => 'carbjetting.store','method'=>'POST')) !!}
    @include('carbjetting.form')
    {!! Form::close() !!}


@endsection

resources/views/carbjetting/edit.blade.php
@extends('layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('carbjetting.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    {!! Form::model($garage, ['method' => 'PATCH','route' => ['carbjetting.update', $garage->id]]) !!}
    @include('carbjetting.form')
    {!! Form::close() !!}


@endsection

resources/views/carbjetting/form.blade.php
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            {!! Form::hidden('garage_id', request('id'), null) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Pilot</strong>
            {!! Form::text('pilot', null, array('placeholder' => 'Pilot','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Main Jet</strong>
            {!! Form::text('main', null, array('placeholder' => 'Main Jet','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Clip Position</strong>
            {!! Form::text('clip_position', null, array('placeholder' => 'Clip Position','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Needle</strong>
            {!! Form::text('needle', null, array('placeholder' => 'Needle','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Float Height</strong>
            {!! Form::text('float_height', null, array('placeholder' => 'Float Height','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Idle Screw</strong>
            {!! Form::text('idle_screw', null, array('placeholder' => 'Idle Screw','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Air Fuel Screw</strong>
            {!! Form::text('airfuel_screw', null, array('placeholder' => 'Air Fuel Screw','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/carbjetting/index.blade.php
<h2>Carburetor</h2>
<a class="btn btn-success" href="{{ route('carbjetting.create') }}"> Add a Carb Setting </a>


@if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
@endif


<table class="table table-bordered">
    <tr>
        <th>Pilot</th>
        <th>Main</th>
        <th>Clip Position</th>
        <th>Float Height</th>
        <th>Idle Screw</th>
        <th>Air Fuel Screw</th>
    </tr>

    {{--  <tr>
          <td>{{ $carbjetting->pilot}}</td>
          <td>{{ $carbjetting->main}}</td>
          <td>{{ $carbjetting->clip_pos}}</td>
          <td>{{ $carbjetting->float_height}}</td>
          <td>{{ $carbjetting->idle_screw}}</td>
          <td>{{ $carbjetting->airfuel_screw}}</td>
          <td>
              <a class="btn btn-info" href="{{ route('carbjetting.show',$vehicle->id) }}">Show</a>
              <a class="btn btn-primary" href="{{ route('carbjetting.edit',$vehicle->id) }}">Edit</a>
              {!! Form::open(['method' => 'DELETE','route' => ['carbjetting.destroy', $vehicle->id],'style'=>'display:inline']) !!}
              {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
              {!! Form::close() !!}
          </td>
      </tr>--}}
</table>

resources/views/carbjetting/show.blade.php
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2><strong>Carburetor Settings</strong></h2>
        </div>

        <div style="float: right">
            <a class="btn btn-primary" href="{{ route('drive.edit',$garage->id) }}">Edit</a>

            {!! Form::open(['method' => 'DELETE','route' => ['drive.destroy', $garage->id],'style'=>'float:right']) !!}
            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
            {!! Form::close() !!}
        </div>

    </div>
</div>

@foreach ($garage->carbjetting as $carbjetting)

<table class="table table-bordered">
        <tr>
            <th>Pilot</th>
            <th>Main</th>
            <th>Needle</th>
            <th>Clip Position</th>
            <th>Float Height</th>
            <th>Idle Screw</th>
            <th>Air Fuel Screw</th>
        </tr>

        <tr>
            <td>{{ $carbjetting->pilot}}</td>
            <td>{{ $carbjetting->main}}</td>
            <td>{{ $carbjetting->needle}}</td>
            <td>{{ $carbjetting->clip_position}}</td>
            <td>{{ $carbjetting->float_height}}</td>
            <td>{{ $carbjetting->idle_screw}}</td>
            <td>{{ $carbjetting->airfuel_screw}}</td>
        </tr>
    </table>

@endforeach