routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GarageController@index');

Route::resource('garage','GarageController');

Route::resource('carbjetting','CarbController');

Route::resource('drive','DriveController');

Route::resource('journal','JournalController');

Route::resource('suspension','SuspensionController');

Auth::routes();

/*Route::get('/home', [
    'middleware' => ['auth'],
    'uses' => function () {
        echo "You are allowed to view this page!";
    }]);*/

app/Garage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Garage extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id','user_id','year', 'make', 'model'
    ];

    public function journals()
    {
        return $this->hasMany('App\Journal');
    }

    /**
     * Get the User record associated with the Garage item.
     */
    public function users()
    {
        return $this->belongsTo('App\User');
    }


    /**
     * Get the carbjetting record associated with the garage item.
     */
    public function carbjettings()
    {
        return $this->hasMany('App\carbJetting');
    }


    /**
     * Get the drive record associated with the garage item.
     */
    public function drives()
    {
        return $this->hasMany('App\Drive');
    }

    /**
     * Get the Suspension record associated with the garage item.
     */
    public function suspensions()
    {
        return $this->hasMany('App\Suspension');
    }


}

app/Http/Controllers/GarageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Garage;

class GarageController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id = \Auth::user()->id;
        $garage = Garage::where('user_id', $id)->get();
        return view('garage.index' ,compact('garage'))
            ->with('i', (request()->input('page', 1) -1) * 5);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $id = \Auth::user()->id;
        return view('garage.create', ['id' => $id]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'year' => 'required',
            'make' => 'required',
            'model' => 'required',
        ]);



        $garage = Garage::create($request->all());

        $this->imageUpload($request, $garage);



        return redirect()->route('garage.show', compact('garage'))
            ->with('success','Garage record created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $garage = Garage::find($id);
        return view('garage.show', compact('garage'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $garage = Garage::find($id);
        return view('garage.edit',compact('garage'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        request()->validate([
            'year' => 'required',
            'make' => 'required',
            'model' => 'required',
        ]);
        Garage::find($id)->update($request->all());
        return redirect()->route('garage.index')
            ->with('success','Garage record created successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id){

        $garage = Garage::find($id);

        $garage->suspensions()->delete();
        $garage->carbjettings()->delete();
        $garage->drives()->delete();
        $garage->journals()->delete();
        $garage->delete();


        return redirect()->route('garage.index')
            ->with('success','Garage record deleted successfully');
    }


    public function imageUpload(Request $request, Garage $garage)

    {


        $this->validate($request, [

            'image' => 'image|mimes:jpeg,png,jpg,gif,svg|max:4096',

        ]);

        $image = $request->file('image');



        $ext = $image->getClientOriginalExtension();

        $image->storeAs('public/images/' . auth()->id() . '/' . $garage->id, "image.{$ext}");


        return back()->with('success', 'Image Upload successful');
    }

}

resources/views/garage/create.blade.php
@extends('layouts.app')


@section('content')
    <div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Vehicle</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('garage.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    {!! Form::open(array('route' => 'garage.store','method'=>'POST', 'enctype'=>'multipart/form-data')) !!}
    @include('garage.form', ['id' => $id])
    {!! Form::close() !!}


    </div>


@endsection

resources/views/garage/edit.blade.php
@extends('layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Vehicle</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('garage.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    {!! Form::model($garage, ['method' => 'PATCH','route' => ['garage.update', $garage->id]]) !!}
    @include('garage.form')
    {!! Form::close() !!}


@endsection

resources/views/garage/form.blade.php
<div class="row">
    <div class="form-group">
        {!! Form::hidden('user_id', $id, null) !!}
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Year</strong>
            {!! Form::text('year', null, array('placeholder' => 'Year','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Make</strong>
            {!! Form::text('make', null, array('placeholder' => 'Make','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Model</strong>
            {!! Form::text('model', null, array('placeholder' => 'Make','class' => 'form-control')) !!}
        </div>
    </div>

    <div class="row cancel">
        <div class="col-md-4">
            {!! Form::file('image', array('class' => 'image')) !!}
        </div>
    </div>


    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>

</div>

resources/views/garage/index.blade.php
@extends('layouts.app')


@section('content')
    <div class="container">
        <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>MotoSolutions Garage</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('garage.create') }}"> Add a vehicle to the Garage</a>
            </div>
        </div>
        </div>



    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


    <table class="table table-bordered">
        <tr>
            <th>Year</th>
            <th>Make</th>
            <th>Model</th>
        </tr>


       @foreach ($garage as $vehicle)
            <tr>
                <td>{{ $vehicle->year}}</td>
                <td>{{ $vehicle->make}}</td>
                <td>{{ $vehicle->model}}</td>
                <td>
                    <div class="pull-right">
                    <a class="btn btn-info" href="{{ route('garage.show',$vehicle->id) }}">Show</a>
                    <a class="btn btn-primary" href="{{ route('garage.edit',$vehicle->id) }}">Edit</a>
                    {!! Form::open(['method' => 'DELETE','route' => ['garage.destroy', $vehicle->id],'style'=>'display:inline']) !!}
                    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                    {!! Form::close() !!}
                    </div>
                </td>
            </tr>
        @endforeach

    </table>
    </div>






@endsection

resources/views/garage/show.blade.php
@extends('layouts.app')


@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-12 margin-tb">

                <h2><strong>{{ $garage->year}} {{ $garage->make}} {{ $garage->model}}</strong>

                    <a class="btn btn-primary" href="{{ route('garage.index') }}" style="float: right"> Back</a>

                </h2>
            </div>
        </div>

        <table class="table table-striped table-bordered ">
            <img src="{{Storage::disk()->url('images' . '/' . auth()->id() .'/' . $garage->id . '/' . 'image.jpg')}}" height="40%" width="40%">
        </table>


        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif


        <table class="table table-bordered">

            @if(count($garage->journal) > 0)
                @include('journal.show')
            @else
                <a class="btn btn-success" href="{{ route('journal.create', ['id' => $garage->id]) }}"> Create Journal
                    Entry</a>
            @endif

            @if(count($garage->drive) > 0)
                @include('drive.show')
            @else
                <a class="btn btn-success" href="{{ route('drive.create', ['id' => $garage->id]) }}"> Create Drive</a>
            @endif

            @if(count($garage->carbjetting) > 0)
                @include('carbjetting.show')
            @else
                <a class="btn btn-success" href="{{ route('carbjetting.create', ['id' => $garage->id]) }}"> Create Carb
                    Jetting Specs</a>
            @endif

            @if(count($garage->suspension) > 0)
                @include('suspension.show')
            @else
                <a class="btn btn-success" href="{{ route('suspension.create', ['id' => $garage->id]) }}"> Create
                    Suspension Settings</a>
            @endif


        </table>


        {{{$garage}}}

        {{--  @include('drive.show')

          @include('carbjetting.index')

          @include('suspension.index')

          @include('journal.index')
      --}}
    </div>
@endsection